name: calciunit
description: "Android-compatible unit converter that connects quantitative units with intuitive, familiar objects."

publish_to: "none"

version: 0.2.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.3.2
  rational: ^2.2.3
  intl: any
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  decimal: ^3.0.2
  hooks_riverpod: ^2.5.2
  path_provider: ^2.1.4
  path: ^1.9.0
  go_router: ^14.3.0
  freezed_annotation: ^2.4.4
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  freezed: ^2.5.7
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3

flutter:
  fonts:
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP.ttf
  uses-material-design: true
